[package]
name = "structs"
version = "0.1.0"
edition = "2021"
authors = ["Diogo Dias <das.dias6@gmail.com>"]
description = "An example using structs to build geometry."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
